name: hello-world-workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello-test-world
        run: echo "Hello-Test_World"
        shell: bash

  goofbye-test:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye-test-world
        run: echo "godbye test world"
        shell: bash
